<?php

namespace Flower\CoreBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Flower\ModelBundle\Entity\Clients\Contact;
use Flower\ModelBundle\Entity\Clients\ContactSource;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Flower\ModelBundle\Entity\Clients\Account;

/**
 * Description of LoadContactSourceData
 *
 * @author Juan Manuel Aguero <jaguero@flowcode.com.ar>
 */
class LoadContactSourceData extends AbstractFixture implements FixtureInterface, ContainerAwareInterface, OrderedFixtureInterface
{

    /**
     * @var ContainerInterface
     */
    private $container;

    public function load(ObjectManager $manager)
    {

        $contactSource1 = new ContactSource();
        $contactSource1->setName("Social Network");

        $manager->persist($contactSource1);
        $this->addReference('contact-source-social1', $contactSource1);

        $contactSource2 = new ContactSource();
        $contactSource2->setName("Autogenerated");

        $manager->persist($contactSource2);
        $this->addReference('contact-source-social2', $contactSource2);

        $manager->flush();
    }

    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

    public function getOrder()
    {
        return 8;
    }

}
