<?php

namespace Flower\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationChannelRepository extends EntityRepository
{
}
